[package]
name = "mopac-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"

[dev-dependencies]
approx = "0.5.1"
psqs = { git = "https://github.com/ntBre/psqs" }
tempfile = "3.14.0"