permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: Cache mopac
        id: cache-mopac
        uses: actions/cache@v4
        with:
          path: |
            mopac/build/mopac
            mopac/build/libmopac.so.1
            mopac/include/mopac.h
          key: ${{ runner.os }}-build-mopac
      - name: install mopac
        if: steps.cache-mopac.outputs.cache-hit != 'true'
        run: |
            sudo apt install -y python3 python3-numpy
            git clone https://github.com/openmopac/mopac.git
            cd mopac
            mkdir build
            cd build
            cmake ..
            make
      - name: cargo test --locked
        env:
          MOPAC_PATH: ${{ github.workspace }}/mopac
        run: cargo test --workspace --locked --all-features --all-targets -- --include-ignored
